[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src/", "src"]

[contracts]
hub = ["src/hub.cairo"]
router-aggregator = ["src/router_aggregators/router_aggregator.cairo"]
router-aggregator_proxy = ["src/router_aggregators/router_proxy.cairo"]
solver-registry = ["src/solver_registry.cairo"]
trade-executor = ["src/trade_executor.cairo"]
solver = ["src/solvers/solver.cairo"]
spf-olver = ["src/solvers/spf_solver.cairo"]
single-swap-solver = ["src/solvers/single_swap_solver.cairo"]
heuristic-splitter = ["src/solvers/heuristic_splitterV2.cairo"]
heuristic-splitter_V3 = ["src/solvers/heuristic_splitterV3.cairo"]
graddesc_solver = ["src/solvers/graddesc_solver.cairo"]

[test]
target = ["tests"]

[profile.devnet.deploy]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.deploy]
network = "alpha-goerli"
