["protostar.config"]
protostar_version = "v0.4.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
hub = [
    "./src/hub.cairo",
]
router_aggregator = [
    "./src/router_aggregators/router_aggregator.cairo",
]
solver_registry = [
    "./src/solver_registry.cairo",
]
trade_executor = [
    "./src/trade_executor.cairo",
]
spf_solver = [
    "./src/solvers/spf_solver.cairo",
]
single_swap_solver = [
    "./src/solvers/single_swap_solver.cairo",
]
heuristic_splitter = [
    "./src/solvers/heuristic_splitter.cairo",
]
mock_jedi_router = [
    "./src/mocks/mock_jedi_router.cairo",
]
mock_price_oracle = [
    "./src/mocks/mock_price_oracle.cairo",
]

[profile.devnet.protostar.deploy]
gateway-url="http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"