name: TESTS

on: [push, pull_request, pull_request_target]

env:
  PROTOSTAR_VERSION: 0.5.0
  DEBUG: False

jobs:
  protostar-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      
      - name: install dependencies
        run: make setup

      - name: start mainnet fork
        run: make mainnet-fork

      - name: run integration tests
        run: make test-integration

  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Amarna
        uses: crytic/amarna-action@v0.1.1
        id: amarna
        continue-on-error: true
        with:
          sarif: results.sarif
          target: 'src/'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.amarna.outputs.sarif }}
          checkout_path: '/github/workspace'