name: TESTS

on: [push, pull_request, pull_request_target]

jobs:
  compilation-tests:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    #----------------------------------------------
    # install Protostar
    #----------------------------------------------
    - name: Install Protostar
      uses: wei/curl@master
      with:
        args: https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh
      run: source /home/runner/.bashrc  
    #----------------------------------------------
    # install further dependencies
    #----------------------------------------------    
    - name: Install dependencies
      run: make setup
    #----------------------------------------------
    # Check Contract Format
    #----------------------------------------------
    - name: Check Format
      run: |
        make format-check   
    #----------------------------------------------
    # Compile Contracts
    #----------------------------------------------

  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Amarna
        uses: crytic/amarna-action@v0.1.1
        id: amarna
        continue-on-error: true
        with:
          sarif: results.sarif
          target: 'src/'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.amarna.outputs.sarif }}
          checkout_path: '/github/workspace'