name: TESTS

on: [push, pull_request, pull_request_target]

env:
  PROTOSTAR_VERSION: 0.5.0
  DEBUG: False

jobs:
  protostar-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash -s -- -v $PROTOSTAR_VERSION
      
      - name: Install protostar dependencies
        run: /home/runner/.protostar/dist/protostar/protostar install OpenZeppelin/cairo-contracts@v0.5.0

      - name: Compile smart contracts
        run: /home/runner/.protostar/dist/protostar/protostar build --cairo-path ./lib/cairo_contracts/src --disable-hint-validation

      - name: Run protostar tests
        run: /home/runner/.protostar/dist/protostar/protostar test ./tests

  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Amarna
        uses: crytic/amarna-action@v0.1.1
        id: amarna
        continue-on-error: true
        with:
          sarif: results.sarif
          target: 'src/'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.amarna.outputs.sarif }}
          checkout_path: '/github/workspace'